[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "flask-login>=0.6.3",
    "flask-session>=0.8.0",
    "telethon>=1.39.0",
    "twilio>=9.4.6",
]
